# Test request
GET http://localhost:8090
Content-Type: application/json

# about
GET http://localhost:8090/about
Content-Type: application/json

# about
GET http://localhost:8090
Content-Type: application/json

# about
GET http://localhost:8090/projects
Content-Type: application/json

# about
GET http://localhost:8090/projects/n1
Content-Type: application/json

# about
POST http://localhost:8090/projects
Content-Type: application/json

{
  "name": "name",
  "test": "test",
  "proj-name": "n1"
}



# Another test request
GET https://api.github.com
User-Agent: Emacs Restclient